### ISSUE TITLE
Question about SBMP

### ISSUE THREAD

**Issue by Somiacao** [mkolodiy/s-bpm-modeler#1]
Hello,First introduce my environment.It is jdk1.8.0_181 and mysql is mysql-5.6.41-winx64.I hava ran your mysql script. But I confuse why there is not a database.In addition,I can open the localhost:3000,but it is impossible to login,because it did not correspond to mysql.
I cannot find what and where the problem encountered
Thank you very much if you can solve my problem.

**Comment by mkolodiy** [comment]
Hello @Somiacao, this project doesn't use Java or MySql. For running this project you need NodeJs and MongoDB. Please refer to the [usage](https://github.com/mkolodiy/s-bpm-modeler#usage) section for more details.

**Comment by Somiacao** [comment]
Actually,I want to ask is the question about https://github.com/stefanstaniAIM/IPPR2016.And I observed that you are one of the contributer. But why I ask you?because I cannot contact the author.Thank you.

**Comment by mkolodiy** [comment]
Unfortunately I was not involved in the development of the part your question refers to. Therefore I can't answer your question.
